export default [
  { label: 'Annual Snowfall', name: 'annualSnowfall', units: ' in' },
  { label: 'Acreage', name: 'acreage', units: ' acres' },
  { label: 'Vertical', name: 'vertical', units: ' ft' },
  { label: 'Summit Elevation', name: 'summitElevation', units: ' ft' },
  { label: 'Lifts', name: 'lifts', units: '' },
  { label: 'Terrain Parks', name: 'terrainParks', units: '' },
  { label: 'Beginner Terrain', name: 'beginnerPercent', units: '%' },
  { label: 'Intermediate Terrain', name: 'intermediatePercent', units: '%' },
  { label: 'Expert Terrain', name: 'expertPercent', units: '%' },
  { label: 'State/Province', name: 'stateOrProvince', units: '' },
  { label: 'Country', name: 'country', units: '' },
  { label: 'Nearest Airport', name: 'airportNearest', units: '' },
  { label: 'Drive Time', name: 'driveTime', units: 'minutes' },
  { label: 'Snowboards Allowed', name: 'snowboardsAllowed', units: '' },
];
